apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot
spec:
  selector:
    matchLabels:
      app: polkadot
  replicas: 1
  template:
    metadata:
      labels:
        app: polkadot
    spec:
      containers:
      - name: polkadot
        image: parity/polkadot:latest
        args: ["--name", "polkadot","--chain","polkadot-local","--ws-external","--rpc-external", "--rpc-cors", "all"]
        ports:
        - containerPort: 9944
          name: wss
        - containerPort: 9933
          name: rpc
        - containerPort: 30333
          name: p2p
        volumeMounts:
        - mountPath: /polkadot
          name: polkadot
      volumes:
      - name: polkadot
        persistentVolumeClaim:
          claimName: polkadot-pvc
      securityContext:
        runAsUser: 1000
      serviceAccountName: polkadot      


