apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot-rc
spec:
  selector:
    matchLabels:
      app: polkadot-rc
  replicas: 1
  template:
    metadata:
      labels:
        app: polkadot-rc
    spec:
      containers:
      - name: polkadot-rc
        image: parity/polkadot:latest
        args: ["--name", "opsumo-test","--chain","polkadot-pc","--ws-external","--rpc-external", "--rpc-cors", "all"]
        ports:
        - containerPort: 9944
          name: wss
        - containerPort: 9933
        - containerPort: 30333
        volumeMounts:
        - mountPath: /polkadot-rc
          name: polkadot-rc
      volumes:
      - name: polkadot-rc
        persistentVolumeClaim:
          claimName: polkadot-rc-pvc


