apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot
spec:
  selector:
    matchLabels:
      app: polkadot
  replicas: 1
  template:
    metadata:
      labels:
        app: polkadot
    spec:
      containers:
      - name: polkadot
        image: parity/polkadot:latest
        args: ["--name", "opsumo-test","--chain","westend","--ws-external","--rpc-external", "--prometheus-external"]
        ports:
        - containerPort: 9944
          name: wss
        - containerPort: 9933
          name: rpc
        - containerPort: 30333
          name: p2p
        volumeMounts:
        - mountPath: /data
          name: polkadot
      volumes:
      - name: polkadot
        persistentVolumeClaim:
          claimName: polkadot-pvc
      securityContext:
        runAsUser: 0
          
