apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadotjs
spec:
  selector:
    matchLabels:
      app: polkadotjs
  replicas: 1
  template:
    metadata:
      labels:
        app: polkadotjs
    spec:
      containers:
      - name: polkadotjs
        image: edmcbee/polkadotjs:latest
        env:
        - name: WS_URL
          value: "ws://polkadot-wss.polkadot.svc:9944"
        ports:
        - containerPort: 8000
          name: web  
        
