kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-admin
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- kube-admin-user
groups:
- kube-admin-group
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT