apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot-pc
spec:
  selector:
    matchLabels:
      app: polkadot-pc
  replicas: 1
  template:
    metadata:
      labels:
        app: polkadot-pc
    spec:
      containers:
      - name: polkadot
        image: parity/polkadot:latest
        args: ["--name", "corpus-test","--chain","polkadot-rc","--ws-external","--rpc-external", "--rpc-cors", "all"]
        ports:
        - containerPort: 9944
          name: wss
        - containerPort: 9933
        - containerPort: 30333
        volumeMounts:
        - mountPath: /polkadot-pc
          name: polkadot-pc
      volumes:
      - name: polkadot-pc
        persistentVolumeClaim:
          claimName: polkadot-pc-pvc


